server:
  port: 8090
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
        use_sql_comments: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
  flyway:
    url: ${DB_URL}
    schemas: NotificationDB
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    locations: "classpath:db/migration"
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
  mustache:
    check-template-location: false
  mail:
    username: "nlohithkumar.18.it@anits.edu.in"
cloud:
  aws:
    region: ${AWS_REGION}
    sqs:
      queue-name: notification-request-queue
twilio:
  account_sid: ${TWILIO_ACCOUNT_SID}
  auth_token: ${TWILIO_AUTH_TOKEN}
  phone_number: ${TWILIO_MOBILE}
sendgrid:
  api:
    key: ${SENDGRID_API_KEY}
user:
    service:
      endpoint: "http://localhost:8084/user/preferences/"