server:
  port: 8090
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
        use_sql_comments: true
  datasource:
    url: jdbc:mysql://localhost:3306/NotificationDB
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    url: jdbc:mysql://localhost:3306/NotificationDB
    schemas: NotificationDB
    user: "root"
    password: "admin"
    locations: "classpath:db/migration"
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
  mustache:
    check-template-location: false
  mail:
    username: "nlohithkumar.18.it@anits.edu.in"
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region: us-west-2
    sqs:
      queue-name: notification-queue
twilio:
  account_sid: ${TWILIO_ACCOUNT_SID}
  auth_token: ${TWILIO_AUTH_TOKEN}
  phone_number: ${TWILIO_PHONE_NUMBER}
sendgrid:
  api:
    key: ${SENDGRID_API_KEY}

user:
  service:
    endpoint: "http://localhost:8084/user/preferences/"
management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]
  metrics:
    export:
      prometheus:
        enabled: true